#spring:
#  application:
#    name: RestApidemo
#  datasource:
#    mysql:
#      url: jdbc:mysql://localhost:3306/mydb
#      username: root
#      password: 1234242
#      driver-class-name: com.mysql.cj.jdbc.Driver
##    oracle:
##      url: jdbc:oracle:thin:@localhost:1521:orcl
##      username: MYSQL80
##      password: 1234242
##      driver-class-name: oracle.jdbc.OracleDriver
#
#server:
#  port: 7473
#
#debug: true
